# Generated by Django 2.0.5 on 2018-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('address', models.CharField(default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('location', models.CharField(default='', max_length=256)),
                ('photo', models.CharField(blank=True, default='', max_length=1024)),
                ('sunday_hours', models.CharField(default='Closed', max_length=256)),
                ('monday_hours', models.CharField(default='Closed', max_length=256)),
            ],
        ),
    ]
