# Generated by Django 2.0.5 on 2018-06-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='description',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='market',
            name='monday_hours',
        ),
        migrations.RemoveField(
            model_name='market',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='market',
            name='sunday_hours',
        ),
    ]
